### PR TITLE
Adapt ACdream and UESTC to their new version 

### PR DESCRIPTION
**Pull request by crccw**
[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v3/28)

### CODE REVIEW

**Comment by 51isoft** [comment]
Reviewed files:
- ajax/admin_deal_replay.php @ r1

---

<sup>**[ajax/admin_deal_replay.php, line 252 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-JmeoXi9Xbtlf-Imhveu)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/ajax/admin_deal_replay.php#L252)):</sup>
Why do you need cookiejar here?

---

<sup>**[composer.lock, line 56 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmepqjzh-q_fwGOEeQr)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/composer.lock#L56)):</sup>
Well, I didn't plan to use composer in v3 :) I just checked that in for fun. lol.
Let's just use standalone php file.

---

<sup>**[functions/pcrawlers.php, line 755 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmeq504FEOdpympZ1LJ)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/functions/pcrawlers.php#L755)):</sup>
Any problem encountered?

---

<sup>**[problem_show.php, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-JmeookxBDrE0i1gvofO)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/problem_show.php#L1)):</sup>
Host locally please.

---

<sup>**[problem_show.php, line 2 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmeog7ZbB90-NfeXyL9)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/problem_show.php#L2)):</sup>
Please only load this when it's UESTC. Remember there's also contest_problem_show

---

<sup>**[utils/migrate_uestc.php, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmep7Jo4SV8V4Q74ugk)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/utils/migrate_uestc.php#L1)):</sup>
Please make sure other users cannot access, ie don't put it on server.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28)

**Comment by crccw** [comment]
<sup>**[ajax/admin_deal_replay.php, line 252 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-JmeoXi9Xbtlf-Imhveu)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/ajax/admin_deal_replay.php#L252)):</sup>
mentioned in the commit log, UESTC requires access the contest page before the rank page, otherwise the request will be denied, so I need JSESSIONID

---

<sup>**[functions/pcrawlers.php, line 755 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmeq504FEOdpympZ1LJ)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/functions/pcrawlers.php#L755)):</sup>
I haven't found any problem that is marked as having SPJ so far.....

---

<sup>**[problem_show.php, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-JmeookxBDrE0i1gvofO)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/problem_show.php#L1)):</sup>
It's huge...50+M...

---

<sup>**[utils/migrate_uestc.php, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmep7Jo4SV8V4Q74ugk)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/utils/migrate_uestc.php#L1)):</sup>
I won't~ I don't plan to use in on production server actually...just run it locally and generate SQL..

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28)

**Comment by crccw** [comment]
<sup>**[composer.lock, line 56 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmepqjzh-q_fwGOEeQr)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/composer.lock#L56)):</sup>
So remove thoes file?

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28)

**Comment by 51isoft** [comment]
<sup>**[composer.lock, line 56 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmepqjzh-q_fwGOEeQr)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/composer.lock#L56)):</sup>
Yes, we can use http://parsedown.org/

---

<sup>**[functions/pcrawlers.php, line 755 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-Jmeq504FEOdpympZ1LJ)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/functions/pcrawlers.php#L755)):</sup>
Okay

---

<sup>**[problem_show.php, line 1 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28#-JmeookxBDrE0i1gvofO)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/0a2776b694e4f12ab91ad4c04a54107dabfc44f2/problem_show.php#L1)):</sup>
Yes, any concerns? The js is pretty small, and I don't think we need the whole package.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/28)

**Pull request merged**
