### PR TITLE
fix hustv replay crawler: url changed

### PR DESCRIPTION
**Pull request by crccw**

### CODE REVIEW

**Comment by suiyuan2009** [comment]
still can't crawl hustv's contest's standing~

**Comment by crccw** [comment]
not deployed yet

**Comment by 51isoft** [comment]
Another thing, I think hustv is vjudge.net now.

**Comment by crccw** [comment]
vjudge.net is 302 to http://acm.hust.edu.cn/vjudge/

**Comment by crccw** [comment]
seems that vjudge.net is for overseas vistors

**Comment by 51isoft** [comment]
Cool, then that's ok.

**Pull request merged**
