### PR TITLE
Add support for Python3

### PR DESCRIPTION
**Pull request by crccw**
[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v3/31)

### CODE REVIEW

**Comment by 51isoft** [comment]
adjlist.js needs to be updated as well

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/31)

**Comment by 51isoft** [comment]
Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/31)

**Comment by crccw** [comment]
adjlist.js is no longer used since #22 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/31)

**Comment by suiyuan2009** [comment]
还没有部署

**Pull request merged**
