### PR TITLE
Add rejudge option in view source dialog EOM

### PR DESCRIPTION
**Pull request by crccw**
click events in the view source dialog should be unbinded to avoid duplicate requests

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v3/24)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
Where is #dtitle

---

<sup>**[js/contest_show.js, line 270 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-B5s73Ikflrhtvjc)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L270)):</sup>
wrap up, $("#sharey').off("click").click(

---

<sup>**[js/contest_show.js, line 282 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-L2KHSmWaUM8Jw4_)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L282)):</sup>
ditto

---

<sup>**[js/contest_show.js, line 293 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-RX1SHDjaXpEfbId)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L293)):</sup>
what's this

---

<sup>**[js/contest_show.js, line 295 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-Q1P2qnP1dbvha_M)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L295)):</sup>
ditto

---

<sup>**[js/status.js, line 219 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-UnoU75AR1FIFS94)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/status.js#L219)):</sup>
ditto

---

<sup>**[js/status.js, line 242 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-WGUDGOi7_iEbMwp)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/status.js#L242)):</sup>
ditto

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
my fault....

---

<sup>**[js/contest_show.js, line 270 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-B5s73Ikflrhtvjc)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L270)):</sup>
Done.

---

<sup>**[js/contest_show.js, line 282 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-L2KHSmWaUM8Jw4_)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L282)):</sup>
Done.

---

<sup>**[js/contest_show.js, line 293 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-RX1SHDjaXpEfbId)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L293)):</sup>
Done.

---

<sup>**[js/contest_show.js, line 295 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-Q1P2qnP1dbvha_M)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/contest_show.js#L295)):</sup>
Done.

---

<sup>**[js/status.js, line 219 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-UnoU75AR1FIFS94)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/status.js#L219)):</sup>
Done.

---

<sup>**[js/status.js, line 242 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji-WGUDGOi7_iEbMwp)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/js/status.js#L242)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
I think you can just move id="dtitle" to the span though.

---

<sup>**[status.php, line 74 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji63WADQFrpOXzESVv)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/69acc08a0947454c484afbab6fe63c72800df1f6/status.php#L74)):</sup>
ditto

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
how about get rid of it?

---

<sup>**[status.php, line 74 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji63WADQFrpOXzESVv)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/69acc08a0947454c484afbab6fe63c72800df1f6/status.php#L74)):</sup>
ditto

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
nope, we use h3 to style. And rejudge button shouldn't be in the header. I think you should put it in dialog body

---

<sup>**[status.php, line 74 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji63WADQFrpOXzESVv)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/69acc08a0947454c484afbab6fe63c72800df1f6/status.php#L74)):</sup>
ditto

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
Done.

---

<sup>**[status.php, line 74 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji63WADQFrpOXzESVv)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/69acc08a0947454c484afbab6fe63c72800df1f6/status.php#L74)):</sup>
Done.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
dtitle?

---

<sup>**[js/contest_show.js, line 91 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjmzjKUEz2wMc_7qJc3)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/contest_show.js#L91)):</sup>
dtitle

---

<sup>**[js/contest_show.js, line 239 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjmzmOW-eAydX-npojH)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/contest_show.js#L239)):</sup>
ditto

---

<sup>**[js/status.js, line 15 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jjmzp6_laTXv_HrKzBY)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/status.js#L15)):</sup>
ditto

---

<sup>**[js/status.js, line 187 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jjmzq1jPu-548meZ2BV)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/status.js#L187)):</sup>
ditto

---

<sup>**[status.php, line 73 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji63WADQFrpOXzESVv)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/69acc08a0947454c484afbab6fe63c72800df1f6/status.php#L73)):</sup>
dtitle

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24)

---

<sup>**[contest_status.php, line 102 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjhzzriqIPl54zY8OkD)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4767e3abead83aa3a114fa44761214eadeba3fa8/contest_status.php#L102)):</sup>
I think it's not necessary, (#statusdialog h3) should be enough.

---

<sup>**[js/contest_show.js, line 91 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjmzjKUEz2wMc_7qJc3)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/contest_show.js#L91)):</sup>
updated

---

<sup>**[js/contest_show.js, line 239 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-JjmzmOW-eAydX-npojH)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/contest_show.js#L239)):</sup>
updated

---

<sup>**[js/status.js, line 15 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jjmzp6_laTXv_HrKzBY)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/status.js#L15)):</sup>
updated

---

<sup>**[js/status.js, line 187 [r4]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jjmzq1jPu-548meZ2BV)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/b398b83d9758220e17c88025802fba66c3a8a614/js/status.js#L187)):</sup>
updated

---

<sup>**[status.php, line 73 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/24#-Jji63WADQFrpOXzESVv)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/69acc08a0947454c484afbab6fe63c72800df1f6/status.php#L73)):</sup>
ditto

---

**Pull request merged**
