### PR TITLE
Add CF Gym

### PR DESCRIPTION
**Pull request by crccw**
Now crawler can deal with 3 situations:
1) all the problems in one pdf
2) problems have their own detail page, like regular problems
3) problems whose link point to a pdf file

However due to the difficulty parsing/splitting pdf files, we cannot
provide single problem pdf for situations 1.

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v3/14)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14)

---

<sup>**[functions/pcrawlers.php, line 105 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14#-JiiME0Z9rDvmfbbGUfe)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/6f8a9c8faf703c4a50726264063b006f0b873c4d/functions/pcrawlers.php#L105)):</sup>
same concern with vjudge.

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14)

---

<sup>**[functions/pcrawlers.php, line 105 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14#-JiiME0Z9rDvmfbbGUfe)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/6f8a9c8faf703c4a50726264063b006f0b873c4d/functions/pcrawlers.php#L105)):</sup>
else i have to copy this function...lol

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14)

---

<sup>**[functions/pcrawlers.php, line 105 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14#-JiiME0Z9rDvmfbbGUfe)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/6f8a9c8faf703c4a50726264063b006f0b873c4d/functions/pcrawlers.php#L105)):</sup>
Personally, I'd prefer treat CF and CFGym as different OJs.

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14)

---

<sup>**[functions/problems.php, line 49 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14#-JioAUZqwIUUJhRjHL9Z)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/3fda6a36ce6117a01ab89b3e13f4da00860f965d/functions/problems.php#L49)):</sup>
Don't forget to update adjlist.js.
And also v2.
For v1, meh, as you like.

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14)

---

<sup>**[functions/problems.php, line 49 [r2]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/14#-JioAUZqwIUUJhRjHL9Z)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/3fda6a36ce6117a01ab89b3e13f4da00860f965d/functions/problems.php#L49)):</sup>
Done.

---

**Pull request merged**
