### PR TITLE
WHU crawler fails to determine non-exist problem

### PR DESCRIPTION
**Pull request by crccw**
WHU will return 403 AND AT THE SAME TIME a webpage containing the Ooooops thing, which will triggle a PHP Warning and file_get_contents returns false.

[Review on Reviewable](https://reviewable.io/reviews/bnuacm/bnuoj-web-v3/15)

### CODE REVIEW

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15)

---

<sup>**[functions/pcrawlers.php, line 1187 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15#-JimYjSawN5RIsTS3jqa)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4b14cd2babda4165360f63ae6d084ca9c8529bb5/functions/pcrawlers.php#L1187)):</sup>
Let's use both of the conditions

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15)

---

<sup>**[functions/pcrawlers.php, line 1187 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15#-JimYjSawN5RIsTS3jqa)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4b14cd2babda4165360f63ae6d084ca9c8529bb5/functions/pcrawlers.php#L1187)):</sup>
the original one won't work...

---

**Comment by 51isoft** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15)

---

<sup>**[functions/pcrawlers.php, line 1187 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15#-JimYjSawN5RIsTS3jqa)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4b14cd2babda4165360f63ae6d084ca9c8529bb5/functions/pcrawlers.php#L1187)):</sup>
I know, in case we might change get_contents to curl. Have a nice fallback

---

**Comment by crccw** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15)

---

<sup>**[functions/pcrawlers.php, line 1187 [r1]](https://reviewable.io:443/reviews/bnuacm/bnuoj-web-v3/15#-JimYjSawN5RIsTS3jqa)** ([raw file](https://github.com/bnuacm/bnuoj-web-v3/blob/4b14cd2babda4165360f63ae6d084ca9c8529bb5/functions/pcrawlers.php#L1187)):</sup>
I'll write a comment for that

---

**Pull request merged**
